Kitty font features & changes to scripts
Changed the opentype font features for JetBrainsMono NFM font.
Changed source directories list in tmux sessionizer script (added
~/dev/*/). Fixed a typo in auto-server script that was preventing it
from starting pnpm & npm dev servers.

diff --git a/.config/scripts/auto-server b/.config/scripts/auto-server
--- a/.config/scripts/auto-server
+++ b/.config/scripts/auto-server
@@ -3,76 +3,81 @@
 directory=$1
 
 if [[ -z $directory ]]; then
-  echo "Error: Directory not provided."
-  exit 1
+	echo "Error: Directory not provided."
+	exit 1
 fi
 
 # === Node.js based stuff ===
 
 # Check for package.json
 if [[ ! -f "$directory/package.json" ]]; then
-  printf "╔════════════════════════════════════════════════════════════╗\n║ No package.json found. Running next check...               ║\n╚════════════════════════════════════════════════════════════╝\n"
+	printf "╔════════════════════════════════════════════════════════════╗\n║ No package.json found. Running next check...               ║\n╚════════════════════════════════════════════════════════════╝\n"
 
 else
-  printf "╔════════════════════════════════════════════════════════════╗\n║ Found package.json. Setting up project...                  ║\n╚════════════════════════════════════════════════════════════╝\n"
+	printf "╔════════════════════════════════════════════════════════════╗\n║ Found package.json. Setting up project...                  ║\n╚════════════════════════════════════════════════════════════╝\n"
 
-  package_manager=""
+	package_manager=""
 
-  if [ -e "bun.lockb" ]; then
-    package_manager="bun"
-  elif [ -e "yarn.lock" ]; then
-    package_manager="yarn"
-  else
-    package_manager="npm"
-  fi
+	if [ -e "bun.lockb" ]; then
+		package_manager="bun"
+	elif [ -e "yarn.lock" ]; then
+		package_manager="yarn"
+	elif [ -e "pnpm-lock.yaml" ]; then
+		package_manager="pnpm"
+	elif [ -e "package-lock.json" ]; then
+		package_manager="npm"
+	else
+		printf "╔════════════════════════════════════════════════════════════╗\n║ No lock file found. Exiting script...                      ║\n╚════════════════════════════════════════════════════════════╝\n"
+		exit 0
+	fi
 
-  dev_script=$(jq -r '.scripts.dev' "$directory/package.json")
+	dev_script=$(jq -r '.scripts.dev' "$directory/package.json")
 
-  # Check for node_modules
-  if [[ ! -d "$directory/node_modules" ]]; then
-    printf "╔════════════════════════════════════════════════════════════╗\n║ No node_modules found. Installing dependencies...          ║\n╚════════════════════════════════════════════════════════════╝\n"
+	# Check for node_modules
+	if [[ ! -d "$directory/node_modules" ]]; then
+		printf "╔════════════════════════════════════════════════════════════╗\n║ No node_modules found. Installing dependencies...          ║\n╚════════════════════════════════════════════════════════════╝\n"
 
-    if ! $package_manager install; then
-      printf "╔════════════════════════════════════════════════════════════╗\n║ Error: Failed to install node dependencies.                ║\n╚════════════════════════════════════════════════════════════╝\n"
+		if ! $package_manager install; then
+			printf "╔════════════════════════════════════════════════════════════╗\n║ Error: Failed to install node dependencies.                ║\n╚════════════════════════════════════════════════════════════╝\n"
 
-      exit 1
-    fi
-  else
-    printf "╔════════════════════════════════════════════════════════════╗\n║ All dependencies are installed. Running dev server...      ║\n╚════════════════════════════════════════════════════════════╝\n"
+			exit 1
+		fi
+	else
+		printf "╔════════════════════════════════════════════════════════════╗\n║ All dependencies are installed. Running dev server...      ║\n╚════════════════════════════════════════════════════════════╝\n"
 
-  fi
+	fi
 
-  # Check for 'dev' script
-  if [[ "$dev_script" != "null" ]]; then
-    if ! $package_manager run dev; then
-      printf "╔════════════════════════════════════════════════════════════╗\n║ Error: Failed to run dev server.                           ║\n╚════════════════════════════════════════════════════════════╝\n"
+	# Check for 'dev' script
+	if [[ "$dev_script" != "null" ]]; then
+		if ! $package_manager run dev; then
+			printf "╔════════════════════════════════════════════════════════════╗\n║ Error: Failed to run dev server.                           ║\n╚════════════════════════════════════════════════════════════╝\n"
 
-      exit 1
-    fi
-  else
-    printf "╔════════════════════════════════════════════════════════════╗\n║ No dev script found. Cancelling operation...               ║\n╚════════════════════════════════════════════════════════════╝\n"
+			exit 1
+		fi
+	else
+		printf "╔════════════════════════════════════════════════════════════╗\n║ No dev script found. Cancelling operation...               ║\n╚════════════════════════════════════════════════════════════╝\n"
 
-  fi
+	fi
 
-  exit
+	exit
 fi
 
 # === GoLang based stuff ===
 
 # Check for go.mod
 if [[ ! -f "$directory/go.mod" ]]; then
-  printf "╔════════════════════════════════════════════════════════════╗\n║ No go.mod found. Running next check...                     ║\n╚════════════════════════════════════════════════════════════╝\n"
+	printf "╔════════════════════════════════════════════════════════════╗\n║ No go.mod found. Running next check...                     ║\n╚════════════════════════════════════════════════════════════╝\n"
 
 else
-  printf "╔════════════════════════════════════════════════════════════╗\n║ Found go.mod. Installing dependencies...                   ║\n╚════════════════════════════════════════════════════════════╝\n"
+	printf "╔════════════════════════════════════════════════════════════╗\n║ Found go.mod. Installing dependencies...                   ║\n╚════════════════════════════════════════════════════════════╝\n"
 
-  if ! go install; then
-    printf "╔════════════════════════════════════════════════════════════╗\n║ Error: Dependency installation failed.                     ║\n╚════════════════════════════════════════════════════════════╝\n"
+	if ! go install; then
+		printf "╔════════════════════════════════════════════════════════════╗\n║ Error: Dependency installation failed.                     ║\n╚════════════════════════════════════════════════════════════╝\n"
 
-    exit 1
-  fi
+		exit 1
+	fi
 
-  exit
+	exit
 fi
 
 # === Nothing found ===
